# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  mappings:
    avatar_image:
      uri_prefix: /images/avatar
      upload_destination: "%kernel.project_dir%/public/images/avatar"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
